import { useEffect, useState } from 'react'
import { StoreContext } from './store'
import { supabase } from '../services/supabase'
const seedProducts = [
  { id: 1, name: 'Pistachio Milk Cake', description: 'Silky, rich and impossibly soft', price: 850, category: 'Bakery Items', stock: 12, image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80' },
  { id: 2, name: 'Desi Ghee Besan Ladoo', description: 'A classic, made the traditional way', price: 480, category: 'Bakery Items', stock: 28, image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80' },
  { id: 3, name: 'Butter Croissant', description: 'Golden layers, baked fresh daily', price: 220, category: 'Bakery Items', stock: 18, image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80' },
  { id: 4, name: 'Chocolate Chip Cookies', description: 'Crisp edges, chewy centre', price: 360, category: 'Biscuits & Snacks', stock: 34, image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=80' },
  { id: 5, name: 'Mango Cream Cake', description: 'A bright summer favourite', price: 1200, category: 'Bakery Items', stock: 8, image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=900&q=80' },
  { id: 6, name: 'Family Tea Pack', description: 'Everyday tea for home and shop', price: 780, category: 'Grocery Items', stock: 20, image: 'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=900&q=80' },
  { id: 7, name: 'Mixed Chocolate Box', description: 'A colourful counter favourite', price: 650, wholesalePrice: 560, category: 'Candies & Chocolates', stock: 40, image: 'https://images.unsplash.com/photo-1575377427642-087cf684f04d?auto=format&fit=crop&w=900&q=80' },
  { id: 8, name: 'Cola Crate', description: 'Shop-size beverage supply', price: 1800, wholesalePrice: 1550, category: 'Wholesale Products', stock: 15, image: 'https://images.unsplash.com/photo-1629203849820-fdd70d49c38e?auto=format&fit=crop&w=900&q=80' },
]
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) || fallback } catch { return fallback } }
const STORE_DEFAULTS = { name: 'Malik Idrees Sweet Shop & U.A Trader', location: 'Chakki Bazar, Samundri', phone: '03104086111' }
export function StoreProvider({ children }) {
  const [session, setSession] = useState(() => read('malik_session', read('idris_session', null))); const [products, setProducts] = useState(() => read('malik_products', read('idris_products', seedProducts))); const [cart, setCart] = useState(() => read('malik_cart', read('idris_cart', []))); const [orders, setOrders] = useState(() => read('malik_orders', read('idris_orders', []))); const [deals, setDeals] = useState(() => read('malik_deals', [{ id: 1, title: 'Better value for your shop', discount: 15 }])); const [ownerSettings, setOwnerSettingsState] = useState(() => read('malik_settings', STORE_DEFAULTS)); const [language, setLanguage] = useState(() => localStorage.getItem('malik_language') || 'en'); const [toast, setToast] = useState('')
  useEffect(() => localStorage.setItem('malik_session', JSON.stringify(session)), [session]); useEffect(() => localStorage.setItem('malik_products', JSON.stringify(products)), [products]); useEffect(() => localStorage.setItem('malik_cart', JSON.stringify(cart)), [cart]); useEffect(() => localStorage.setItem('malik_orders', JSON.stringify(orders)), [orders]); useEffect(() => localStorage.setItem('malik_settings', JSON.stringify(ownerSettings)), [ownerSettings]); useEffect(() => localStorage.setItem('malik_deals', JSON.stringify(deals)), [deals]); useEffect(() => localStorage.setItem('malik_language', language), [language])
  useEffect(() => { if (!supabase) return; supabase.from('products').select('*').order('created_at', { ascending: false }).then(({ data }) => { if (data?.length) setProducts(data) }) }, [])
  useEffect(() => { if (!supabase || session?.role !== 'owner') return; supabase.from('orders').select('*').order('created_at', { ascending: false }).then(({ data }) => { if (data?.length) setOrders(data) }) }, [session?.role])
  const notify = message => setToast(message)
  const login = (identifier, password) => { if (identifier === 'Ayan' && password === '467467467467') { setSession({ role: 'owner', name: 'Ayan' }); notify('Welcome back, Ayan.'); return { ok: true, role: 'owner' } } const users = read('idris_users', []); const user = users.find(item => (item.phone === identifier || item.name === identifier) && item.password === password); if (!user) return { ok: false, error: 'We could not match those details.' }; setSession(user); notify(`Welcome, ${user.name.split(' ')[0]}.`); return { ok: true, role: 'customer' } }
  const register = form => { const users = read('malik_users', read('idris_users', [])); if (users.some(user => user.phone === form.phone)) return { ok: false, error: 'An account with this phone already exists.' }; const user = { ...form, id: Date.now(), role: 'customer', created_at: new Date().toISOString() }; localStorage.setItem('malik_users', JSON.stringify([...users, user])); if (supabase) supabase.from('users').insert([{ name: user.name, phone: user.phone, shop_name: user.shop_name, address: user.address, delivery_address: user.delivery_address, password: user.password, role: user.role }]).then(() => {}); setSession(user); notify('Your account is ready.'); return { ok: true } }
  const logout = () => { setSession(null); notify('You have been signed out.') }; const addToCart = product => { setCart(items => { const existing = items.find(item => item.id === product.id); return existing ? items.map(item => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { ...product, quantity: 1 }] }); notify(`${product.name} added to your basket.`) }; const updateQuantity = (id, quantity) => setCart(items => quantity < 1 ? items.filter(item => item.id !== id) : items.map(item => item.id === id ? { ...item, quantity } : item)); const removeFromCart = id => setCart(items => items.filter(item => item.id !== id))
  const cartTotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const submitOrder = async ({ location, address, name, phone, shopName } = {}) => {
    if (!session || session.role !== 'customer') { notify('Please sign in as a customer before placing an order.'); return { ok: false, error: 'Customer login required.' } }
    if (!cart.length) { notify('Your basket is empty.'); return { ok: false, error: 'Your basket is empty.' } }
    const orderId = String(Date.now()).slice(-8)
    const createdAt = new Date().toISOString()
    const customerName = name || session.name
    const customerPhone = phone || session.phone
    const orderShopName = shopName || session.shop_name || null
    const deliveryAddress = address || session.delivery_address || session.address || ''
    const orderRows = cart.map(item => ({ order_group_id: orderId, user_id: session.id, customer_name: customerName, customer_phone: customerPhone, shop_name: orderShopName, customer_address: session.address || '', delivery_address: deliveryAddress, product_id: item.id, product_name: item.name, product_image: item.image, product_price: item.price, quantity: item.quantity, total_amount: item.price * item.quantity, order_status: 'pending', status: 'pending', products: [item], customer_location: location || null, created_at: createdAt }))
    const localOrder = { id: orderId, user_id: session.id, customer_name: customerName, customer_phone: customerPhone, shop_name: orderShopName, customer_address: session.address || '', delivery_address: deliveryAddress, items: cart, total_amount: cartTotal, status: 'pending', customer_location: location || null, created_at: createdAt }
    if (supabase) { const { error } = await supabase.from('orders').insert(orderRows); if (error) { notify(`Order could not be saved: ${error.message}`); return { ok: false, error: error.message } } }
    setOrders(items => [localOrder, ...items]); setCart([]); notify('Order placed. We will be in touch shortly.'); window.location.href = '/profile'; return { ok: true, order: localOrder }
  }
  const placeOrder = submitOrder
  const getLocation = () => new Promise(resolve => { if (!navigator.geolocation) return resolve('GPS is not available on this device.'); navigator.geolocation.getCurrentPosition(position => resolve(`${position.coords.latitude.toFixed(5)}, ${position.coords.longitude.toFixed(5)}`), () => resolve('Location permission was not granted.')) })
  const addProduct = product => { const newProduct = { ...product, id: Date.now() }; setProducts(items => [newProduct, ...items]); if (supabase) supabase.from('products').insert([{ name: newProduct.name, image: newProduct.image, description: newProduct.description, price: newProduct.price, wholesale_price: newProduct.wholesalePrice || null, category: newProduct.category, stock: newProduct.stock }]).then(() => {}); notify('Product added to your menu.') }; const deleteProduct = id => { setProducts(items => items.filter(item => item.id !== id)); if (supabase) supabase.from('products').delete().eq('id', id).then(() => {}); notify('Product removed.') }; const updateOrder = (id, status) => { setOrders(items => items.map(order => order.id === id || order.order_group_id === id ? { ...order, status, order_status: status } : order)); if (supabase) supabase.from('orders').update({ order_status: status, status }).eq('order_group_id', id).then(() => {}) }; const setOwnerSettings = settings => setOwnerSettingsState(settings); const addDeal = deal => setDeals(items => [{ ...deal, id: Date.now() }, ...items]); const deleteDeal = id => setDeals(items => items.filter(deal => deal.id !== id))
  return <StoreContext.Provider value={{ session, products, deals, cart, orders: session?.role === 'owner' ? orders : orders.filter(order => order.user_id === session?.id), ownerSettings, language, setLanguage, toast, clearToast: () => setToast(''), login, register, logout, addToCart, updateQuantity, removeFromCart, submitOrder, placeOrder, getLocation, addProduct, deleteProduct, updateOrder, setOwnerSettings, addDeal, deleteDeal, cartTotal }}>{children}</StoreContext.Provider>
}
